/**
 * Build the committed corpus index from `corpus/**`.
 *
 * Public entries only (same filter as `scripts/build-corpus.mjs`). Persona
 * files are guardrails, not retrieval chunks. Private/DRAFT articles stay out.
 */

import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

import matter from "gray-matter";
import { z } from "zod";

import { buildBm25Stats, termFrequencies, tokenize } from "./bm25.js";
import { chunkMarkdown } from "./chunker.js";
import { contentSha256 } from "./hash.js";
import { INDEX_VERSION, type CorpusIndex, type IndexedChunk } from "./types.js";

const CorpusFrontmatter = z
  .object({
    slug: z.string().regex(/^[a-z0-9-]+$/, "slug must be kebab-case"),
    title: z.string().min(1),
    kind: z.enum(["project", "article", "faq"]),
    role: z.string().min(1).optional(),
    stack: z.array(z.string().min(1)).optional(),
    outcomes: z.array(z.string().min(1)).optional(),
    visibility: z.enum(["public", "private"]),
  })
  .strict();

const CORPUS_DIRS = ["projects", "articles", "faq"] as const;

export interface CorpusDoc {
  slug: string;
  title: string;
  kind: "project" | "article" | "faq";
  body: string;
  sourcePath: string;
}

export function loadPublicCorpus(repoRoot: string): CorpusDoc[] {
  const corpusDir = join(repoRoot, "corpus");
  const docs: CorpusDoc[] = [];
  for (const dir of CORPUS_DIRS) {
    const full = join(corpusDir, dir);
    if (!existsSync(full)) continue;
    for (const file of readdirSync(full).sort()) {
      if (!file.endsWith(".md")) continue;
      const sourcePath = join(dir, file);
      const { data, content } = matter(readFileSync(join(full, file), "utf8"));
      const parsed = CorpusFrontmatter.safeParse(data);
      if (!parsed.success) {
        throw new Error(
          `corpus-index: ${sourcePath} failed validation: ${parsed.error.message}`,
        );
      }
      if (parsed.data.visibility !== "public") continue;
      docs.push({
        slug: parsed.data.slug,
        title: parsed.data.title,
        kind: parsed.data.kind,
        body: content.trim(),
        sourcePath,
      });
    }
  }
  docs.sort((a, b) => a.slug.localeCompare(b.slug));
  return docs;
}

function chunkId(kind: string, slug: string, chunkIndex: number): string {
  return `${kind}:${slug}:${chunkIndex}`;
}

export function hashesFromDocs(docs: readonly CorpusDoc[]): string[] {
  const hashes: string[] = [];
  for (const doc of docs) {
    const chunks = chunkMarkdown(doc.body, { emitShort: true });
    for (const chunk of chunks) {
      hashes.push(contentSha256(chunk.content));
    }
  }
  hashes.sort();
  return hashes;
}

export function buildIndex(repoRoot: string): CorpusIndex {
  const docs = loadPublicCorpus(repoRoot);
  const chunks: IndexedChunk[] = [];
  for (const doc of docs) {
    const pieces = chunkMarkdown(doc.body, { emitShort: true });
    for (const piece of pieces) {
      const tokens = tokenize(piece.content);
      chunks.push({
        id: chunkId(doc.kind, doc.slug, piece.chunkIndex),
        contentHash: contentSha256(piece.content),
        sourceType: doc.kind,
        sourceId: doc.slug,
        sourceSlug: doc.slug,
        sourceTitle: doc.title,
        headingPath: piece.headingPath,
        content: piece.content,
        tokenCount: piece.tokenCount,
        chunkIndex: piece.chunkIndex,
        termFreqs: termFrequencies(tokens),
        docLength: tokens.length,
      });
    }
  }
  return {
    version: INDEX_VERSION,
    chunks,
    bm25: buildBm25Stats(chunks),
  };
}

export function renderIndexModule(index: CorpusIndex): string {
  return `// GENERATED by \`pnpm index\` — do not edit by hand.
// Source: corpus/{projects,articles,faq}/*.md (visibility:public only).
// Freshness: every SHA-256 must match a current chunk or CI fails.

import type { CorpusIndex } from "./types.js";

export const CORPUS_INDEX: CorpusIndex = ${JSON.stringify(index, null, 2)};
`;
}

/** Stable fingerprint of the hash set — handy for eval staleness later. */
export function hashSetFingerprint(hashes: readonly string[]): string {
  return createHash("sha256").update(hashes.join("\n"), "utf8").digest("hex");
}
