// GENERATED by scripts/build-corpus.mjs — do not edit by hand.
// Source: corpus/**/*.md (visibility:public only). Run `pnpm corpus`.

export interface CorpusEntry {
  slug: string;
  title: string;
  kind: "project" | "article" | "faq";
  role?: string;
  stack?: readonly string[];
  outcomes?: readonly string[];
  body: string;
}

export const CORPUS: Record<string, CorpusEntry> = {
  "about": {
    "slug": "about",
    "title": "Josh Lowe",
    "kind": "faq",
    "role": "AI Engineer & Consultant",
    "stack": [
      "M.S. Computer Science — University of Central Florida"
    ],
    "outcomes": [
      "AI/ML engineer focused on shipping production-grade AI systems",
      "Tech Lead at BidOps AI; independent consulting as jlowe.ai",
      "Available for AI engineering and consulting work"
    ],
    "body": "AI engineer and consultant. I help teams ship AI systems that hold up in\nproduction — and occasionally rebuild my own site as a drivable 3D world. Reach\nout if you have an AI problem worth solving well."
  },
  "bidops": {
    "slug": "bidops",
    "title": "Tech Lead, BidOps AI",
    "kind": "project",
    "role": "Tech Lead",
    "stack": [
      "TypeScript",
      "AWS Bedrock",
      "RAG",
      "PostgreSQL",
      "Next.js"
    ],
    "outcomes": [
      "Took the AI-assisted bidding platform from prototype to production",
      "Designed the language-model + retrieval pipeline behind the product",
      "Set the engineering bar for testing, observability, and reliability"
    ],
    "body": "Leading engineering on AI-assisted bidding workflows — the retrieval, the\nlanguage-model pipelines, and the platform that has to stay up around them. The\ninteresting work is making LLM features behave in production: grounded, tested,\nand honest about their failure modes."
  },
  "digital-twin": {
    "slug": "digital-twin",
    "title": "AI digital twin",
    "kind": "project",
    "role": "AI Engineer",
    "stack": [
      "Claude on Bedrock",
      "AWS Lambda",
      "TypeScript",
      "Zod"
    ],
    "outcomes": [
      "Grounded only in a reviewed corpus — the twin declines to invent facts about Josh",
      "Fail-open by design — any error still ends the stream cleanly, so the chat never hangs",
      "Schema-validated, turn-capped requests bound both the prompt and the Bedrock bill"
    ],
    "body": "The site answers questions about Josh in his own words — a digital twin that\nspeaks _about_ him, never _as_ him. It streams responses from Claude on AWS\nBedrock through a Lambda response stream, grounded in a fixed persona plus the\nsame public corpus that powers the rest of the site, so the twin and the\nportfolio can never drift apart.\n\nThe guardrails are the design. The twin answers only from the corpus, declines\nto invent employers, dates, or metrics, and points hiring questions to the\ncontact page. Requests are schema-validated and turn-capped to bound both the\nprompt and the Bedrock bill, and every failure path ends the stream with a\nfriendly line instead of hanging. When a visitor has explored beacons in the 3D\nworld, what they saw is passed along as a grounding hint."
  },
  "rag": {
    "slug": "rag",
    "title": "RAG that cites its sources",
    "kind": "project",
    "role": "AI Engineer",
    "stack": [
      "AWS Bedrock",
      "Titan Embeddings",
      "pgvector",
      "Reciprocal Rank Fusion"
    ],
    "outcomes": [
      "Hybrid vector + keyword retrieval merged with RRF, then reranked",
      "Numbered citations so users can trust — and check — the answer",
      "Content-hash-gated re-embedding fanned out over background jobs"
    ],
    "body": "Retrieval-augmented generation only earns trust when it shows its work. Hybrid\nsearch, reciprocal rank fusion, a rerank pass, and numbered citations — so the\nmodel's answer points back at the source instead of asking you to take it on\nfaith."
  },
  "reliability": {
    "slug": "reliability",
    "title": "Fail-open by design",
    "kind": "project",
    "role": "Engineer",
    "stack": [
      "Claude on Bedrock",
      "Inngest",
      "PostgreSQL"
    ],
    "outcomes": [
      "LLM moderation that holds content for review instead of wrongly rejecting it",
      "Every external dependency degrades gracefully, never breaking the request",
      "Observability threaded through every span of the pipeline"
    ],
    "body": "Production AI lives or dies on its failure modes. Moderation that fails open\n(hold, don't reject), rate limits that fail open when the limiter is down, and\nobservability that never propagates its own errors — the boring decisions that\nkeep a product trustworthy."
  },
  "velocity": {
    "slug": "velocity",
    "title": "Velocity — this site",
    "kind": "project",
    "role": "Designer & Engineer",
    "stack": [
      "Three.js",
      "WebGPU",
      "React Three Fiber",
      "Rapier",
      "Next.js",
      "Terraform"
    ],
    "outcomes": [
      "A game-quality 3D portfolio with a WebGPU → WebGL2 → 2D progressive fallback",
      "Original physics-driven driving, with content placed in the world",
      "Infrastructure-as-code on AWS and CI-gated performance budgets"
    ],
    "body": "This site is the portfolio — a game-quality 3D world with an AI digital twin,\nrebuilt in public. Built on React Three Fiber and the\nthree.js WebGPU renderer under a strict progressive-enhancement contract: every\nvisitor gets a working experience, down to a 2D shell that search engines and\nscreen readers fully understand."
  }
};

export const CORPUS_SLUGS = ["about","bidops","digital-twin","rag","reliability","velocity"] as const;
