// GENERATED by scripts/build-corpus.mjs — do not edit by hand.
// Source: corpus/**/*.md (visibility:public only). Run `pnpm corpus`.

export interface CorpusEntry {
  slug: string;
  title: string;
  kind: "project" | "article" | "faq";
  role?: string;
  stack?: readonly string[];
  outcomes?: readonly string[];
  body: string;
}

export const CORPUS: Record<string, CorpusEntry> = {
  "about": {
    "slug": "about",
    "title": "Josh Lowe",
    "kind": "faq",
    "role": "AI Engineer & Consultant",
    "stack": [
      "M.S. Computer Science — University of Central Florida"
    ],
    "outcomes": [
      "AI/ML engineer focused on shipping production-grade AI systems",
      "Tech Lead at BidOps AI; independent consulting as jlowe.ai",
      "Available for AI engineering and consulting work"
    ],
    "body": "AI engineer and consultant. I help teams ship AI systems that hold up in\nproduction — and occasionally rebuild my own site as a drivable 3D world. Reach\nout if you have an AI problem worth solving well."
  },
  "bidops": {
    "slug": "bidops",
    "title": "Tech Lead, BidOps AI",
    "kind": "project",
    "role": "Tech Lead",
    "stack": [
      "TypeScript",
      "AWS Bedrock",
      "RAG",
      "PostgreSQL",
      "Next.js"
    ],
    "outcomes": [
      "Took the AI-assisted bidding platform from prototype to production",
      "Designed the language-model + retrieval pipeline behind the product",
      "Set the engineering bar for testing, observability, and reliability"
    ],
    "body": "Leading engineering on AI-assisted bidding workflows — the retrieval, the\nlanguage-model pipelines, and the platform that has to stay up around them. The\ninteresting work is making LLM features behave in production: grounded, tested,\nand honest about their failure modes."
  },
  "rag": {
    "slug": "rag",
    "title": "RAG that cites its sources",
    "kind": "project",
    "role": "AI Engineer",
    "stack": [
      "AWS Bedrock",
      "Titan Embeddings",
      "pgvector",
      "Reciprocal Rank Fusion"
    ],
    "outcomes": [
      "Hybrid vector + keyword retrieval merged with RRF, then reranked",
      "Numbered citations so users can trust — and check — the answer",
      "Content-hash-gated re-embedding fanned out over background jobs"
    ],
    "body": "Retrieval-augmented generation only earns trust when it shows its work. Hybrid\nsearch, reciprocal rank fusion, a rerank pass, and numbered citations — so the\nmodel's answer points back at the source instead of asking you to take it on\nfaith."
  },
  "reliability": {
    "slug": "reliability",
    "title": "Fail-open by design",
    "kind": "project",
    "role": "Engineer",
    "stack": [
      "Claude on Bedrock",
      "Inngest",
      "PostgreSQL"
    ],
    "outcomes": [
      "LLM moderation that holds content for review instead of wrongly rejecting it",
      "Every external dependency degrades gracefully, never breaking the request",
      "Observability threaded through every span of the pipeline"
    ],
    "body": "Production AI lives or dies on its failure modes. Moderation that fails open\n(hold, don't reject), rate limits that fail open when the limiter is down, and\nobservability that never propagates its own errors — the boring decisions that\nkeep a product trustworthy."
  },
  "velocity": {
    "slug": "velocity",
    "title": "Velocity — this site",
    "kind": "project",
    "role": "Designer & Engineer",
    "stack": [
      "Three.js",
      "WebGPU",
      "React Three Fiber",
      "Rapier",
      "Next.js",
      "Terraform"
    ],
    "outcomes": [
      "A game-quality 3D portfolio with a WebGPU → WebGL2 → 2D progressive fallback",
      "Original physics-driven driving, with content placed in the world",
      "Infrastructure-as-code on AWS and CI-gated performance budgets"
    ],
    "body": "The car you are driving is the portfolio. Built on React Three Fiber and the\nthree.js WebGPU renderer under a strict progressive-enhancement contract: every\nvisitor gets a working experience, down to a 2D shell that search engines and\nscreen readers fully understand."
  }
};

export const CORPUS_SLUGS = ["about","bidops","rag","reliability","velocity"] as const;
