/**
 * /design/comp — Liquid Heat single-page comp
 *
 * Internal-only preview proving the Liquid Heat aesthetic in production-
 * quality code before propagating it across nine more sessions. Mounts
 * HeroV2 above ProjectDetailV2 with a hard heat boundary between them.
 *
 * Header / Footer / ChatWidget are skipped at the _app.tsx level for any
 * route under /design (see pages/_app.tsx isDesignPage branch). noindex
 * is set there too — this should never be discoverable via search.
 *
 * Falls back to a hand-authored APR Benchmark fixture if Prisma doesn't
 * have the project locally — the comp must always render so the
 * aesthetic can be evaluated regardless of dev DB state.
 */

import type { GetServerSideProps } from "next";
import HeroV2 from "@/components/_design/HeroV2";
import ProjectDetailV2 from "@/components/_design/ProjectDetailV2";
import prisma from "@/lib/prisma";

interface ComProject {
  title: string;
  shortDescription: string | null;
  longDescription: string | null;
  startDate: string;
  releaseDate: string | null;
  status: string | null;
  techStack: unknown;
  tags: unknown;
}

interface ComPageProps {
  project: ComProject;
  attribution: string | null;
}

const FALLBACK_APR: ComProject = {
  title: "Cross-Model Automated Program Repair Benchmark",
  shortDescription:
    "Evaluating 7 state-of-the-art LLMs on a new benchmark that measures how well models fix human-written bugs, LLM-generated bugs, and code containing both, revealing self-repair bias and the limits of static APR benchmarks contaminated by training data.",
  longDescription:
    "As LLMs become standard tools in software development, evaluating their ability to automatically fix bugs has gotten a lot more complicated. Existing benchmarks like QuixBugs and SWE-Bench suffer from data leakage, which means models might perform well just by memorizing training data rather than actually learning how to do program repair.\n\nThis study introduces a new cross-model benchmark that evaluates 7 leading LLMs, including GPT-5.3 Codex, Claude Opus 4.6, Gemini 3.1 Pro, and others, on their ability to repair bugs across three categories: human-written bugs from established benchmarks, deceptive bugs generated by each LLM, and hybrid scenarios where LLM-generated faults are layered on top of already-buggy human code.\n\nPreliminary results on QuixBugs show near-perfect performance from all models, which highlights the need for more challenging, dynamically generated benchmarks that better reflect real-world program repair.",
  startDate: "2026-01-20T00:00:00.000Z",
  releaseDate: null,
  status: "InProgress",
  techStack: ["Python", "OpenAI API", "Anthropic API", "Google Gemini API"],
  tags: ["academic", "evals"],
};

export default function DesignComp({ project, attribution }: ComPageProps) {
  return (
    <>
      <HeroV2 attribution={attribution} />
      <ProjectDetailV2 project={project} />
    </>
  );
}

export const getServerSideProps: GetServerSideProps<ComPageProps> = async () => {
  let project: ComProject = FALLBACK_APR;
  let attribution: string | null = null;

  try {
    const [welcome, dbProject] = await Promise.all([
      prisma.welcome.findFirst({ orderBy: { createdAt: "desc" } }),
      prisma.project.findFirst({
        where: {
          OR: [
            { slug: "cross-model-apr-benchmark" },
            { title: { contains: "Automated Program Repair", mode: "insensitive" } },
          ],
        },
      }),
    ]);

    if (welcome?.briefBio) {
      attribution = welcome.briefBio;
    }

    if (dbProject) {
      project = {
        title: dbProject.title,
        shortDescription: dbProject.shortDescription ?? dbProject.description ?? null,
        longDescription: dbProject.longDescription ?? null,
        startDate:
          dbProject.startDate instanceof Date
            ? dbProject.startDate.toISOString()
            : String(dbProject.startDate),
        releaseDate:
          dbProject.releaseDate instanceof Date ? dbProject.releaseDate.toISOString() : null,
        status: dbProject.status ?? null,
        techStack: dbProject.techStack ?? [],
        tags: dbProject.tags ?? [],
      };
    }
  } catch {
    // DB unavailable — fall back to the fixture so the comp still renders.
  }

  return { props: { project, attribution } };
};
