/* App data — copy pulled from https://www.jlowe.ai */
window.__APP_DATA = {
  owner: {
    name: "Josh Lowe",
    handle: "jlowe.ai",
    role: "AI Engineer & Consultant",
    tagline: "Building What's Next",
    focus: "privacy-preserving ML",
    subrole: "MSCS Student @ UCF · Research Assistant at AI MIND Lab @ UCF",
    summary: "I'm a machine learning researcher at UCF fine-tuning vision-language models for cardiac MRI analysis. I have Dual Bachelor's degrees in CS and Mathematics from FSU. I like building things that solve novel problems. I'm seeking an internship in ML, Data Science, SWE, or PM for Summer 2026.",
    shortBio: "Building intelligent systems and production-grade AI applications that solve real-world problems.",
  },
  techBadges: ["Python", "PyTorch", "AWS", "Next.js", "React.js", "Flask"],
  projects: [
    {
      id: "apr-benchmark",
      title: "Cross-Model Automated Program Repair Benchmark",
      status: "In Progress",
      tag: "academic",
      short: "Evaluating 7 state-of-the-art LLMs on a new benchmark that measures how well models fix human-written bugs, LLM-generated bugs, and code containing both, revealing self-repair bias and the limits of static APR benchmarks contaminated by training data.",
      tech: ["Python", "OpenAI API", "Anthropic API"],
      featured: true,
    },
    {
      id: "ace-service",
      title: "Ace Service Group LLC Website",
      status: "Completed",
      tag: "freelancing",
      short: "Professional marketing website with admin CMS for a construction company, featuring a 3D animated logo and full content management system.",
      tech: ["Next.js", "React.js", "TypeScript"],
      featured: true,
    },
    {
      id: "fed-mia",
      title: "Evaluating Mitigation Strategies for Membership Inference Attacks in Federated Learning",
      status: "Completed",
      tag: "academic",
      short: "Evaluates differential privacy as a defense against membership inference attacks in federated learning, revealing counterintuitive results where DP increased attack success on overfit models.",
      tech: ["Python", "PyTorch", "Flower"],
      featured: true,
    },
    {
      id: "nutrillava",
      title: "NutriLLaVA",
      status: "Completed",
      tag: "academic-project",
      short: "Multimodal AI app comparing LLaVA 1.5 vs 1.6 for generating personalized recipes from fridge/pantry photos based on dietary goals.",
      tech: ["Python", "PyTorch", "Hugging Face Transformers"],
      featured: true,
    },
    {
      id: "swesphere",
      title: "SWESphere",
      status: "In Progress",
      tag: "independent-project",
      short: "A full-stack Twitter-like social media platform with web, API, and mobile apps supporting real-time notifications, multi-language i18n, and comprehensive security.",
      tech: ["Python", "Flask", "FastAPI"],
      featured: false,
    },
    {
      id: "jlowe-ai",
      title: "jlowe.ai",
      status: "In Progress",
      tag: "portfolio",
      short: "A production-deployed full-stack portfolio platform built with Next.js, featuring 76 React components, 32 RESTful API endpoints, and a custom CMS. Includes a Three.js-powered 3D animated background, real-time analytics with 13 custom events, and comprehensive test automation with 2,962 tests achieving 77% code coverage.",
      tech: ["Next.js 15", "React 18", "Node.js"],
      featured: false,
    },
    {
      id: "barstool",
      title: "Barstool Scheduler",
      status: "Completed",
      tag: "academic-project",
      short: "A Linux kernel module implementing a bar simulation with waiters, customers, tables, and waiting queues using kthreads and system calls.",
      tech: ["C", "Linux Kernel API", "Procfs"],
      featured: false,
    },
    {
      id: "c-shell",
      title: "C Shell",
      status: "Completed",
      tag: "academic-project",
      short: "A custom Unix shell implementation in C featuring command parsing, I/O redirection, piping, background processes, and built-in commands.",
      tech: ["C", "GCC", "Make"],
      featured: false,
    },
    {
      id: "hacked-news",
      title: "Hacked News",
      status: "Completed",
      tag: "independent-project",
      short: "A secure news aggregation site powered by Hacker News API with Auth0 authentication and automated hourly article updates.",
      tech: ["Python", "Flask", "SQLite3"],
      featured: false,
    },
  ],
  experience: [
    {
      role: "Research Assistant",
      org: "AI MIND Lab at University of Central Florida",
      years: "Dec 2025 — Present",
      detail: "Conducting research on vision-language models for automated cardiac cine-MRI analysis. Developing fine-tuning and transfer learning methods using the ACDC dataset, which contains cardiac cine-MRI data from 150 different patients across 5 different pathologies. The goal is to enable clinical reasoning on multimodal medical imaging data, teaching models to interpret and explain what they see in these scans.",
    },
    {
      role: "QA Engineer Intern",
      org: "CSC",
      years: "May 2023 — Aug 2023",
      detail: "Worked on quality assurance for CSC Connect, a fintech application. Authored over 35 test suites in Azure DevOps and identified 17 critical defects before they reached production. Engineered Cypress automation scripts for regression testing and collaborated on an international team to analyze defect patterns.",
    },
  ],
  education: [
    {
      degree: "Master of Science in Computer Science",
      school: "University of Central Florida",
      years: "Sep 2025 — Expected May 2027",
      coursework: ["Machine Learning", "Natural Language Processing", "Cybersecurity", "Malware Analysis", "Advanced Algorithms"],
    },
    {
      degree: "Bachelor of Science in Computer Science",
      school: "Florida State University",
      years: "Aug 2019 — Dec 2023",
      coursework: ["Data Structures & Algorithms", "Computer Architecture", "Operating Systems", "Software Engineering", "Unix", "Secure Programming", "Distributed Computing", "Theory of Computation"],
    },
    {
      degree: "Bachelor of Science in Mathematics",
      school: "Florida State University",
      years: "Aug 2019 — Dec 2023",
      coursework: ["Calculus", "Differential Equations", "Discrete Mathematics", "Probability & Statistics", "Physics", "Linear Algebra", "Abstract Algebra", "Number Theory", "Real Analysis"],
    },
  ],
  certifications: [
    { name: "AWS Certified Developer - Associate", issuer: "AWS" },
  ],
  articles: [
    { title: "Shipping agents that don't hallucinate themselves into a corner", topic: "LLM Systems", date: "2026 · 03", read: "8 min" },
    { title: "Why your RAG retrieval is actually a ranking problem", topic: "Retrieval", date: "2026 · 02", read: "6 min" },
    { title: "Evaluation harnesses I wish I'd built sooner", topic: "Infrastructure", date: "2026 · 01", read: "11 min" },
    { title: "Federated learning without the privacy theater", topic: "Security", date: "2025 · 11", read: "9 min" },
  ],
  hobbies: ["Weight Lifting", "Philadelphia Sports", "Reading", "Business"],
  social: [
    { key: "email", label: "Email", handle: "joshlowe.cs@gmail.com", href: "mailto:joshlowe.cs@gmail.com" },
    { key: "github", label: "GitHub", handle: "joshrlowe", href: "https://github.com/joshrlowe" },
    { key: "linkedin", label: "LinkedIn", handle: "in/joshrlowe", href: "https://linkedin.com/in/joshrlowe" },
    { key: "handshake", label: "Handshake", handle: "joshrlowe", href: "https://ucf.joinhandshake.com/profiles/joshrlowe" },
  ],
};
