import SEO from "@/components/SEO";
import { Button } from "@/components/ui";

/**
 * Custom 404. Statically generated by Next — must stay free of data fetching
 * so it can be served for any unmatched route.
 */
export default function NotFoundPage() {
  return (
    <>
      <SEO
        title="Page Not Found"
        description="The page you're looking for doesn't exist or has moved."
        noindex
      />
      <div className="section relative z-10 flex items-center justify-center min-h-[70vh] px-4 sm:px-6 lg:px-8">
        <div className="container mx-auto max-w-2xl text-center">
          <p
            className="text-8xl sm:text-9xl font-bold mb-6 font-[family-name:var(--font-oswald)]"
            aria-hidden="true"
          >
            <span className="gradient-text">404</span>
          </p>
          <h1 className="text-3xl sm:text-4xl font-bold text-[var(--color-text-primary)] mb-4 font-[family-name:var(--font-oswald)]">
            Page Not Found
          </h1>
          <p
            className="text-lg text-[var(--color-text-secondary)] mb-10 mx-auto"
            style={{ maxWidth: "80%" }}
          >
            The page you&apos;re looking for doesn&apos;t exist or has moved. Let&apos;s get you
            back on track.
          </p>
          <div className="flex flex-wrap items-center justify-center gap-4">
            <Button href="/" size="lg">
              Back Home
            </Button>
            <Button href="/projects" variant="secondary" size="lg">
              View Projects
            </Button>
            <Button href="/articles" variant="secondary" size="lg">
              Read Articles
            </Button>
          </div>
        </div>
      </div>
    </>
  );
}
