import SEO from "@/components/SEO";
import { Button } from "@/components/ui";

/**
 * Custom 500. Statically generated by Next — must stay free of data fetching
 * (anything dynamic here could itself fail while rendering the error page).
 */
export default function ServerErrorPage() {
  return (
    <>
      <SEO
        title="Something Went Wrong"
        description="An unexpected error occurred. Please try again shortly."
        noindex
      />
      <div className="section relative z-10 flex items-center justify-center min-h-[70vh] px-4 sm:px-6 lg:px-8">
        <div className="container mx-auto max-w-2xl text-center">
          <p
            className="text-8xl sm:text-9xl font-bold mb-6 font-[family-name:var(--font-oswald)]"
            aria-hidden="true"
          >
            <span className="gradient-text">500</span>
          </p>
          <h1 className="text-3xl sm:text-4xl font-bold text-[var(--color-text-primary)] mb-4 font-[family-name:var(--font-oswald)]">
            Something Went Wrong
          </h1>
          <p
            className="text-lg text-[var(--color-text-secondary)] mb-10 mx-auto"
            style={{ maxWidth: "80%" }}
          >
            An unexpected error occurred on our end. Please refresh the page or come back shortly.
          </p>
          <div className="flex flex-wrap items-center justify-center gap-4">
            <Button href="/" size="lg">
              Back Home
            </Button>
            <Button href="/contact" variant="secondary" size="lg">
              Contact Me
            </Button>
          </div>
        </div>
      </div>
    </>
  );
}
