#!/usr/bin/env node
/**
 * Corpus → typed module. Reads corpus/<kind>/*.md, validates frontmatter with
 * zod (build FAILS on malformed frontmatter or an unknown key), keeps only
 * `visibility: public`, and emits apps/web/src/data/corpus.generated.ts.
 *
 * The corpus is the single source of truth shared with Phase-5 RAG ingestion;
 * this script is the world's compile-time view of it. No runtime fs — the
 * static export imports a plain typed module.
 *
 * Run: `pnpm corpus`. CI regenerates and fails on drift (git diff).
 */
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import matter from "gray-matter";

import { CorpusFrontmatter } from "./corpus-schema.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CORPUS_DIR = join(ROOT, "corpus");
const OUT = join(ROOT, "apps", "web", "src", "data", "corpus.generated.ts");
const DIRS = ["projects", "articles", "faq"];

const entries = [];
for (const dir of DIRS) {
  const full = join(CORPUS_DIR, dir);
  if (!existsSync(full)) continue;
  for (const file of readdirSync(full).sort()) {
    if (!file.endsWith(".md")) continue;
    const { data, content } = matter(readFileSync(join(full, file), "utf8"));
    const parsed = CorpusFrontmatter.safeParse(data);
    if (!parsed.success) {
      console.error(`corpus: ${dir}/${file} failed validation`);
      console.error(JSON.stringify(parsed.error.format(), null, 2));
      process.exit(1);
    }
    const fm = parsed.data;
    if (fm.visibility !== "public") continue;
    entries.push({
      slug: fm.slug,
      title: fm.title,
      kind: fm.kind,
      ...(fm.role ? { role: fm.role } : {}),
      ...(fm.stack ? { stack: fm.stack } : {}),
      ...(fm.outcomes ? { outcomes: fm.outcomes } : {}),
      body: content.trim(),
    });
  }
}

entries.sort((a, b) => a.slug.localeCompare(b.slug));

const slugs = entries.map((e) => e.slug);
const dupes = [...new Set(slugs.filter((s, i) => slugs.indexOf(s) !== i))];
if (dupes.length) {
  console.error(`corpus: duplicate slug(s): ${dupes.join(", ")}`);
  process.exit(1);
}

const record = Object.fromEntries(entries.map((e) => [e.slug, e]));
const out = `// GENERATED by scripts/build-corpus.mjs — do not edit by hand.
// Source: corpus/**/*.md (visibility:public only). Run \`pnpm corpus\`.

export interface CorpusEntry {
  slug: string;
  title: string;
  kind: "project" | "article" | "faq";
  role?: string;
  stack?: readonly string[];
  outcomes?: readonly string[];
  body: string;
}

export const CORPUS: Record<string, CorpusEntry> = ${JSON.stringify(record, null, 2)};

export const CORPUS_SLUGS = ${JSON.stringify(slugs)} as const;
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out);
console.log(
  `corpus: wrote ${entries.length} public entries → apps/web/src/data/corpus.generated.ts`,
);
